services:
  - type: web
    name: flask-file-upload
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production